{% set name = "django-simple-history" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-simple-history-{{ version }}.tar.gz
  sha256: bff0a756238b2fa048ea3ffe8224b4edd421559123ff9ce5c27682c37c6a7702

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.7,<3.11
    - django >=3.2

test:
  imports:
    - simple_history
about:
  home: https://github.com/treyhunner/django-simple-history
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Store model history and view/revert changes from admin site.'
  description: 
    django-simple-history stores Django model state on every create/update/delete.
  doc_url: https://django-simple-history.readthedocs.io/
  dev_url: https://github.com/treyhunner/django-simple-history

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
